/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class trading_MarketChannelImpl */

#ifndef _Included_trading_MarketChannelImpl
#define _Included_trading_MarketChannelImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     trading_MarketChannelImpl
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_trading_MarketChannelImpl_connect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
