/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_NativeInterface */

#ifndef _Included_demo_NativeInterface
#define _Included_demo_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_NativeInterface
 * Method:    native_helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demo_NativeInterface_native_1helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
